# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c776cd519d13ed9bfb1cceacc48ce03026b7338ad531cfc7dd2842e96e5931af912dcb45de25b671a8a1f529d76c5c5b3e3e7aa9e6a2e1419975b2871063f674

test:
  secret_key_base: 499d0d99a87258095a14ffba2a43a6db0a0e6f6a15d89564266dc4b82471f203401c68e71610c0fe4ee801be7e72dcf46ef6cf629114b3612d33137c333fcbf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
